name: macOS

on: [push]

jobs:
  build:
    env:
      PACKAGE_NAME: _PACKAGE_NAME

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Build
      run: brew bundle
    - name: Build
      run: swift build
    - name: Lint
      run: swiftformat --lint . && swiftlint
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/${{ env.PACKAGE_NAME }}PackageTests.xctest/Contents/MacOS/${{ env.PACKAGE_NAME }}PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash) -F github -F macOS -n ${{ github.sha }}
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Build Documentation
      run: sourcedocs generate --spm-module ${{ env.PACKAGE_NAME }} --output-folder docs
    - name: Verify Valid Swift Package
      run: swift package dump-package | jq -e ".products | length > 0"
    - name: CocoaPods Action
      run: pod lib lint
    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash) -F github -F macos -n ${{ github.sha }}
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add docs
        git diff-index --quiet HEAD || git commit -m "[github action] Update Docs"
        git push
